// Define the sections data with additional fields
export const channelSections = [
  {
    id: 1,
    title: "Basics",
    description: "Learn the fundamentals of Spanish including basic greetings and simple phrases.",
    level: "A1",
    difficulty: "Easy" as const,
    progress: 38, // Updated to match completedSteps/totalSteps
    completedSteps: 3,
    totalSteps: 8,
    isUnlocked: true,
    isActive: true,
    color: "#58CC02",
  },
  {
    id: 2,
    title: "Phrases",
    description: "Master common phrases and expressions used in everyday conversations.",
    level: "A1",
    difficulty: "Medium" as const,
    progress: 0,
    completedSteps: 0,
    totalSteps: 6,
    isUnlocked: false,
    isActive: false,
    color: "#A560E8",
  },
  {
    id: 3,
    title: "Grammar",
    description: "Learn essential grammar rules including verb conjugations and sentence structure.",
    level: "A1",
    difficulty: "Medium" as const,
    progress: 0,
    completedSteps: 0,
    totalSteps: 10,
    isUnlocked: false,
    isActive: false,
    color: "#1CB0F6",
  },
  {
    id: 4,
    title: "Vocabulary",
    description: "Expand your vocabulary with words related to food, travel, and daily activities.",
    level: "A2",
    difficulty: "Hard" as const,
    progress: 0,
    completedSteps: 0,
    totalSteps: 12,
    isUnlocked: false,
    isActive: false,
    color: "#FF9600",
  },
]
